package com.roycemars.royalgold.core.ui.theme
import androidx.compose.ui.graphics.Color

/*
// ChatGPT generated colors for the app - test what's better

val primaryLight = Color(0xFF9C47F2)         // Vivid purple from top card
val onPrimaryLight = Color(0xFFFFFFFF)

val primaryContainerLight = Color(0xFFC18CFA) // Softer purple for highlights
val onPrimaryContainerLight = Color(0xFF220032)

val secondaryLight = Color(0xFF6B60FF)        // Gradient violet-blue
val onSecondaryLight = Color(0xFFFFFFFF)

val secondaryContainerLight = Color(0xFFA8A0FF)
val onSecondaryContainerLight = Color(0xFF1C004A)

val tertiaryLight = Color(0xFFF586D4)         // Pink tone from income/expense icons
val onTertiaryLight = Color(0xFF3A002B)

val tertiaryContainerLight = Color(0xFFFFC0EB)
val onTertiaryContainerLight = Color(0xFF4F003C)

val backgroundLight = Color(0xFFF5E9FF)       // Light purple-glass background
val onBackgroundLight = Color(0xFF1B1327)

val surfaceLight = Color(0xFFF3EDFB)
val onSurfaceLight = Color(0xFF1C162A)

val errorLight = Color(0xFFFF4F5E)            // From “Expence” bar red
val onErrorLight = Color(0xFFFFFFFF)

val outlineLight = Color(0xFF9E8CB2)
val surfaceVariantLight = Color(0xFFE6D4F3)
val onSurfaceVariantLight = Color(0xFF463955)
 */

val primaryLight = Color(0xFF7836C4)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9253DF)
val onPrimaryContainerLight = Color(0xFFFFFBFF)
val secondaryLight = Color(0xFF6D528D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBBCFF)
val onSecondaryContainerLight = Color(0xFF624882)
val tertiaryLight = Color(0xFFA52674)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC5418E)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF7FF)
val onBackgroundLight = Color(0xFF1E1A22)
val surfaceLight = Color(0xFFFFF7FF)
val onSurfaceLight = Color(0xFF1E1A22)
val surfaceVariantLight = Color(0xFFEADEF2)
val onSurfaceVariantLight = Color(0xFF4B4453)
val outlineLight = Color(0xFF7D7484)
val outlineVariantLight = Color(0xFFCEC2D5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF332F38)
val inverseOnSurfaceLight = Color(0xFFF7EEFA)
val inversePrimaryLight = Color(0xFFD9B9FF)
val surfaceDimLight = Color(0xFFE0D7E3)
val surfaceBrightLight = Color(0xFFFFF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAF0FD)
val surfaceContainerLight = Color(0xFFF4EBF7)
val surfaceContainerHighLight = Color(0xFFEEE5F1)
val surfaceContainerHighestLight = Color(0xFFE9DFEC)

val primaryLightMediumContrast = Color(0xFF4E0093)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF8A4AD7)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF432A62)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF7C619D)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF6C0049)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFFBB3986)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FF)
val onBackgroundLightMediumContrast = Color(0xFF1E1A22)
val surfaceLightMediumContrast = Color(0xFFFFF7FF)
val onSurfaceLightMediumContrast = Color(0xFF131018)
val surfaceVariantLightMediumContrast = Color(0xFFEADEF2)
val onSurfaceVariantLightMediumContrast = Color(0xFF3A3342)
val outlineLightMediumContrast = Color(0xFF574F5F)
val outlineVariantLightMediumContrast = Color(0xFF726A7A)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF332F38)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF7EEFA)
val inversePrimaryLightMediumContrast = Color(0xFFD9B9FF)
val surfaceDimLightMediumContrast = Color(0xFFCCC4D0)
val surfaceBrightLightMediumContrast = Color(0xFFFFF7FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFAF0FD)
val surfaceContainerLightMediumContrast = Color(0xFFEEE5F1)
val surfaceContainerHighLightMediumContrast = Color(0xFFE3DAE6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD7CFDB)

val primaryLightHighContrast = Color(0xFF40007B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF641CB0)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF381F57)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF573D76)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF5A003C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF8C0A60)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FF)
val onBackgroundLightHighContrast = Color(0xFF1E1A22)
val surfaceLightHighContrast = Color(0xFFFFF7FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEADEF2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF302938)
val outlineVariantLightHighContrast = Color(0xFF4E4655)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF332F38)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD9B9FF)
val surfaceDimLightHighContrast = Color(0xFFBEB6C2)
val surfaceBrightLightHighContrast = Color(0xFFFFF7FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF7EEFA)
val surfaceContainerLightHighContrast = Color(0xFFE9DFEC)
val surfaceContainerHighLightHighContrast = Color(0xFFDAD1DE)
val surfaceContainerHighestLightHighContrast = Color(0xFFCCC4D0)

val primaryDark = Color(0xFFD9B9FF)
val onPrimaryDark = Color(0xFF460085)
val primaryContainerDark = Color(0xFFB071FE)
val onPrimaryContainerDark = Color(0xFF2A0054)
val secondaryDark = Color(0xFFD8BAFD)
val onSecondaryDark = Color(0xFF3D245C)
val secondaryContainerDark = Color(0xFF563D76)
val onSecondaryContainerDark = Color(0xFFCAACEE)
val tertiaryDark = Color(0xFFFFAFD5)
val onTertiaryDark = Color(0xFF620041)
val tertiaryContainerDark = Color(0xFFE85EAB)
val onTertiaryContainerDark = Color(0xFF3E0027)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF16121A)
val onBackgroundDark = Color(0xFFE9DFEC)
val surfaceDark = Color(0xFF16121A)
val onSurfaceDark = Color(0xFFE9DFEC)
val surfaceVariantDark = Color(0xFF4B4453)
val onSurfaceVariantDark = Color(0xFFCEC2D5)
val outlineDark = Color(0xFF978D9F)
val outlineVariantDark = Color(0xFF4B4453)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9DFEC)
val inverseOnSurfaceDark = Color(0xFF332F38)
val inversePrimaryDark = Color(0xFF7A39C7)
val surfaceDimDark = Color(0xFF16121A)
val surfaceBrightDark = Color(0xFF3C3741)
val surfaceContainerLowestDark = Color(0xFF100D15)
val surfaceContainerLowDark = Color(0xFF1E1A22)
val surfaceContainerDark = Color(0xFF221E27)
val surfaceContainerHighDark = Color(0xFF2D2831)
val surfaceContainerHighestDark = Color(0xFF38333C)

val primaryDarkMediumContrast = Color(0xFFE9D4FF)
val onPrimaryDarkMediumContrast = Color(0xFF37006C)
val primaryContainerDarkMediumContrast = Color(0xFFB071FE)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFE9D4FF)
val onSecondaryDarkMediumContrast = Color(0xFF311850)
val secondaryContainerDarkMediumContrast = Color(0xFFA184C3)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFCFE3)
val onTertiaryDarkMediumContrast = Color(0xFF4F0034)
val tertiaryContainerDarkMediumContrast = Color(0xFFE85EAB)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF16121A)
val onBackgroundDarkMediumContrast = Color(0xFFE9DFEC)
val surfaceDarkMediumContrast = Color(0xFF16121A)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4B4453)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE4D8EB)
val outlineDarkMediumContrast = Color(0xFFB9AEC0)
val outlineVariantDarkMediumContrast = Color(0xFF968D9E)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE9DFEC)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2831)
val inversePrimaryDarkMediumContrast = Color(0xFF631AAF)
val surfaceDimDarkMediumContrast = Color(0xFF16121A)
val surfaceBrightDarkMediumContrast = Color(0xFF48424C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF09060D)
val surfaceContainerLowDarkMediumContrast = Color(0xFF201C24)
val surfaceContainerDarkMediumContrast = Color(0xFF2B262F)
val surfaceContainerHighDarkMediumContrast = Color(0xFF36313A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF413C45)

val primaryDarkHighContrast = Color(0xFFF8ECFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD6B4FF)
val onPrimaryContainerDarkHighContrast = Color(0xFF14002D)
val secondaryDarkHighContrast = Color(0xFFF8ECFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFD4B6F8)
val onSecondaryContainerDarkHighContrast = Color(0xFF14002D)
val tertiaryDarkHighContrast = Color(0xFFFFEBF1)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFA9D2)
val onTertiaryContainerDarkHighContrast = Color(0xFF1F0012)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF16121A)
val onBackgroundDarkHighContrast = Color(0xFFE9DFEC)
val surfaceDarkHighContrast = Color(0xFF16121A)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4B4453)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF8ECFF)
val outlineVariantDarkHighContrast = Color(0xFFCABFD1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE9DFEC)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF631AAF)
val surfaceDimDarkHighContrast = Color(0xFF16121A)
val surfaceBrightDarkHighContrast = Color(0xFF544E58)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF221E27)
val surfaceContainerDarkHighContrast = Color(0xFF332F38)
val surfaceContainerHighDarkHighContrast = Color(0xFF3F3943)
val surfaceContainerHighestDarkHighContrast = Color(0xFF4A454E)







