package com.roycemars.royalgold.core.ui.theme.royal
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFFFDD0B)
val onPrimaryLight = Color(0xFF000000)
val primaryContainerLight = Color(0xFFFFDD0B)
val onPrimaryContainerLight = Color(0xFF000000)
val secondaryLight = Color(0xFFFF107B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFF107B)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF550F72)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF550F72)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFFF107B)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF550F72)
val surfaceVariantLight = Color(0xFFFFFFFF)
val onSurfaceVariantLight = Color(0xFF550F72)
val outlineLight = Color(0xFF84727D)
val outlineVariantLight = Color(0xFFD7C0CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313031)
val inverseOnSurfaceLight = Color(0xFFF4EFF1)
val inversePrimaryLight = Color(0xFFFFB957)
val surfaceDimLight = Color(0xFFDDD9DA)
val surfaceBrightLight = Color(0xFFFDF8F9)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F2F4)
val surfaceContainerLight = Color(0xFFF2EBFA)
val surfaceContainerHighLight = Color(0xFFECE7E8)
val surfaceContainerHighestLight = Color(0xFFE6E1E3)

val primaryDark = Color(0xFFFFDD0B)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFFFFDD0B)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFFF107B)
val onSecondaryDark = Color(0xFFFFFFFF)
val secondaryContainerDark = Color(0xFFFF107B)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFF550F72)
val onTertiaryDark = Color(0xFFFFFFFF)
val tertiaryContainerDark = Color(0xFF550F72)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFF107B)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF000000)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF16101E)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF16101e)
val onSurfaceVariantDark = Color(0xFFC881E5)
val outlineDark = Color(0xFF9F8B97)
val outlineVariantDark = Color(0xFF52424C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E1E3)
val inverseOnSurfaceDark = Color(0xFF313031)
val inversePrimaryDark = Color(0xFF835400)
val surfaceDimDark = Color(0xFF141314)
val surfaceBrightDark = Color(0xFF3A393A)
val surfaceContainerLowestDark = Color(0xFF0F0E0F)
val surfaceContainerLowDark = Color(0xFF1D1A24)
val surfaceContainerDark = Color(0xFF1D1A24)
val surfaceContainerHighDark = Color(0xFF2B292B)
val surfaceContainerHighestDark = Color(0xFF403C48)






