package com.roycemars.royalgold.core.ui.theme.space
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5800D8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7133F4)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF5D5F5F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFFFFF)
val onSecondaryContainerLight = Color(0xFF747676)
val tertiaryLight = Color(0xFF000000)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF201926)
val onTertiaryContainerLight = Color(0xFF8B8091)
val errorLight = Color(0xFFB60055)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFE4006C)
val onErrorContainerLight = Color(0xFFFFFBFF)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1A24)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1D1A24)
val surfaceVariantLight = Color(0xFFE7DFF5)
val onSurfaceVariantLight = Color(0xFF494456)
val outlineLight = Color(0xFF7A7488)
val outlineVariantLight = Color(0xFFCBC3D9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F3A)
val inverseOnSurfaceLight = Color(0xFFF5EEFD)
val inversePrimaryLight = Color(0xFFCFBDFF)
val surfaceDimLight = Color(0xFFDED7E6)
val surfaceBrightLight = Color(0xFFFDF7FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F1FF)
val surfaceContainerLight = Color(0xFFF2EBFA)
val surfaceContainerHighLight = Color(0xFFEDE5F5)
val surfaceContainerHighestLight = Color(0xFFE7E0EF)

val primaryDark = Color(0xFF9D79FF)
val onPrimaryDark = Color(0xFFFFFFFF)
val primaryContainerDark = Color(0xFF9D79FF)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFFFFFFF)
val onSecondaryDark = Color(0xFF2F3131)
val secondaryContainerDark = Color(0xFFE2E2E2)
val onSecondaryContainerDark = Color(0xFF636565)
val tertiaryDark = Color(0xFFCFC2D5)
val onTertiaryDark = Color(0xFF352D3C)
val tertiaryContainerDark = Color(0xFF0C0612)
val onTertiaryContainerDark = Color(0xFF807586)
val errorDark = Color(0xFFFFB1C3)
val onErrorDark = Color(0xFF66002C)
val errorContainerDark = Color(0xFFFF4B89)
val onErrorContainerDark = Color(0xFF41001A)
val backgroundDark = Color(0xFF15121C)
val onBackgroundDark = Color(0xFFE7E0EF)
val surfaceDark = Color(0xFF15121C)
val onSurfaceDark = Color(0xFFE7E0EF)
val surfaceVariantDark = Color(0xFF494456)
val onSurfaceVariantDark = Color(0xFFCBC3D9)
val outlineDark = Color(0xFF948DA2)
val outlineVariantDark = Color(0xFF494456)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E0EF)
val inverseOnSurfaceDark = Color(0xFF322F3A)
val inversePrimaryDark = Color(0xFF6C2CEF)
val surfaceDimDark = Color(0xFF15121C)
val surfaceBrightDark = Color(0xFF3B3743)
val surfaceContainerLowestDark = Color(0xFF0F0D17)
val surfaceContainerLowDark = Color(0xFF1D1A24)
val surfaceContainerDark = Color(0xFF211E29)
val surfaceContainerHighDark = Color(0xFF2C2833)
val surfaceContainerHighestDark = Color(0xFF37333E)






